### ISSUE TITLE
First time trying this out

### ISSUE THREAD

**Issue by andrevidela** [soloturn/swift-aur#1]
Hi, it's my first time trying out an AUR package and I get the same error as your CI 

```
swift-language/src/llvm-project/compiler-rt/lib/tsan/dd/dd_interceptors.cpp:225:20: error: redefinition of 'realpath'
```
Can you maybe enlighten me as to what's usually the procedure for a fix?

**Comment by soloturn** [comment]
hey cool andre, and you probably chose one of the few which does not build :)

i reported it here as i hoped an upstream fix would be preferable: https://bugs.swift.org/browse/SR-13082. am trying varun gandhi's suggestions. now hard coded into the build-aur-action: https://github.com/soloturn/build-aur-action/commit/48ca1a38bc69dea9a2320afa183645203f1d5158 . 

if varun is right, it would mean if one installs glibc-dev in other linux distros it would fail the same way. in arch the packages are simpler and not split in runtime and dev, so the header file is there all the time. making it work for arch then should make it work for other linux distros as well.

michael hansen before tried to patch swift, and / or the swift build:
https://aur.archlinux.org/cgit/aur.git/log/?h=swift-language

**Comment by soloturn** [comment]
@andrevidela meanwhile i know the cause. 

    # By default in /etc/makepkg.conf this is "-D_FORTIFY_SOURCE=2"
    # Which will break `compiler-rt`
    unset CPPFLAGS

https://aur.archlinux.org/packages/swift-language-git now build and produces a package. could you try it?

i switched the build so that it should produce a package and publish it if it happens to run shorter than 6 hours and does not get cancelled:
https://github.com/soloturn/swift-aur/actions?query=workflow%3A%22swift-language-git+ci%22
