### ISSUE TITLE
CI Builds are broken

### ISSUE THREAD

**Issue by ProfFan** [soloturn/swift-aur#3]
Hi,

Thanks for the package! I noticed that the CI builds are failing. Probably it is related to an outdated arch image?

**Comment by ProfFan** [comment]
https://bugs.archlinux.org/task/69563

**Comment by soloturn** [comment]
it should take [the latest image](https://github.com/soloturn/build-aur-action/blob/master/Dockerfile). the bug you referenced says the reason is systemd-nspawn and docker on ubuntu-20, with [glibc 2.33-4](https://github.com/archlinux/svntogit-packages/commits/packages/glibc/trunk) it should be fixed. strange strange.  maybe i am overlooking something.

**Comment by ProfFan** [comment]
It's because the Actions runtime is still using an older runc : https://github.com/actions/virtual-environments/issues/2658

**Comment by ProfFan** [comment]
appears now it's timing out...

**Comment by soloturn** [comment]
this is a github restriction, it gets killed if its running 6h. i am not too sure where to host it or how to split up the build to make it reliably finish early enough. @MaxDesiatov proposed at one point to use sccache they do for swiftasm:

- https://github.com/swiftwasm/swift/blob/swiftwasm/utils/build-toolchain 
- https://github.com/swiftwasm/swift/blob/swiftwasm/.github/workflows/build-toolchain.yml 

in swift-aur this is not correctly done most likely.

**Comment by soloturn** [comment]
close it at the moment - nobody working on it. github sometimes has more power or swift build changed so sometimes it takes only 4.5 hours and it goes through ...
